# Uncomment the next line to define a global platform for your project
# platform :ios, '14.4'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'QuickRead' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickRead
  pod 'Alamofire'
  pod 'SDWebImage'
  #pod 'SkeletonView'

end
